from django.urls import path, include
from . import views

urlpatterns = [
    path('login/', views.admin_login, name='admin_login'),
    path('logout/', views.admin_logout, name='admin_logout'),
    
    path('', views.admin_home, name='admin_home'),
    path('portfolio/', views.admin_portfolio, name='admin_portfolio'),
    path('portfolio/edit/<int:pk>/', views.admin_portfolio, name='edit_portfolio'),
    path('portfolio/delete/<int:pk>/', views.delete_portfolio, name='delete_portfolio'),
    path('gallery/', views.admin_gallery, name='admin_gallery'),
    path('gallery/edit/<int:pk>/', views.admin_gallery, name='edit_gallery'),
    path('gallery/delete/<int:pk>/', views.delete_gallery, name='delete_gallery'),
    path('admin/team/', views.team_admin, name='team_admin'),
    path('admin/team/edit/<int:pk>/', views.edit_team, name='edit_team'),
    path('admin/team/delete/<int:pk>/', views.delete_team, name='delete_team'),
    path('careers/', views.admin_careers, name='admin_careers'),
    path('careers/edit/<int:pk>/', views.admin_careers, name='edit_job'),
    path('careers/delete/<int:pk>/', views.delete_job, name='delete_job'),
    path('facilities/', views.admin_facilities, name='admin_facilities'),
    path('facilities/edit/<int:pk>/', views.admin_facilities, name='edit_facility'),
    path('facilities/delete/<int:pk>/', views.delete_facility, name='delete_facility'),
    path('blog/', views.admin_blog, name='admin_blog'),
    path('blog/edit/<int:pk>/', views.admin_blog, name='edit_blog'),
    path('blog/delete/<int:pk>/', views.delete_blog, name='delete_blog'),
    path('faq/', views.admin_faq, name='admin_faq'),
    path('faq/edit/<int:pk>/', views.admin_faq, name='edit_faq'),
    path('faq/delete/<int:pk>/', views.delete_faq, name='delete_faq'),
    path('terms/', views.admin_terms, name='admin_terms'),
    path('terms/edit/<int:pk>/', views.admin_terms, name='edit_term'),
    path('terms/delete/<int:pk>/', views.delete_term, name='delete_term'),
    
    path('privacy/', views.admin_privacy, name='admin_privacy'),
    path('privacy/edit/<int:pk>/', views.admin_privacy, name='edit_privacy'),
    path('privacy/delete/<int:pk>/', views.delete_privacy, name='delete_privacy'),
    path('featured/', views.manage_featured, name='manage_featured'),
    path('featured/edit/<int:pk>/', views.manage_featured, name='edit_featured'),
    path('featured/delete/<int:pk>/', views.delete_featured, name='delete_featured'),
    path('featured/', views.manage_featured, name='manage_featured'),
    path('featured/edit/<int:pk>/', views.manage_featured, name='edit_featured'),
    path('featured/delete/<int:pk>/', views.delete_featured, name='delete_featured'),
    path('testimonials/', views.admin_testimonials, name='admin_testimonials'),
    path('testimonials/edit/<int:pk>/', views.admin_testimonials, name='edit_testimonial'),
    path('testimonials/delete/<int:pk>/', views.delete_testimonial, name='delete_testimonial'),
    path('bookings/', views.admin_bookings, name='admin_booking'),
    path('bookings/delete/<int:pk>/', views.delete_booking, name='delete_booking'),
    path('inquiry/', views.admin_inquiry, name='admin_inquiry'),
    path('inquiry/delete/<int:pk>/', views.delete_inquiry, name='delete_inquiry'),
    
]
