# Generated by Django 6.0.2 on 2026-02-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('social', 'Social'), ('custom', 'Custom')], max_length=50)),
                ('custom_category', models.CharField(blank=True, max_length=100, null=True)),
                ('guests', models.IntegerField()),
                ('event_date', models.DateField()),
                ('image', models.ImageField(upload_to='featured_events/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
