# Generated by Django 6.0.2 on 2026-02-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_place', models.CharField(help_text='e.g. Full-time • Remote', max_length=255)),
                ('experience', models.CharField(help_text='e.g. 3+ years experience', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
