# Generated by Django 6.0.2 on 2026-02-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Set order: 1, 2, 3...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
