# Generated by Django 6.0.2 on 2026-02-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_testimonial'),
        ('admins', '0011_privacypolicy_delete_privacy'),
    ]

    operations = [
    ]
