# Generated by Django 6.0.2 on 2026-02-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='ContactEnquiry',
        ),
    ]
